name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Build site
        run: bundle exec jekyll build
      # Removed GitHub Pages deployment step as we're now using Vercel
